#include <gtest/gtest.h>

#include <cstdint>
#include <filesystem>
#include <fstream>
#include <memory>
#include <string>

#include "TiOfdParser.hpp"
#include "Variable.hpp"
#include "VariableHandler.hpp"

/*
 * Reading a C2000 symbol file.
 *
 * Two things are checked here that no other test can check: the unit
 * conversion, because a C2000 counts memory in 16 bit words while the probe
 * counts in bytes, and the walk over the dump, on a document written by hand so
 * that it says exactly what the walk is expected to answer.
 *
 * The unit conversion is the one that fails quietly. An address that is not
 * doubled reads valid memory that belongs to another variable, and a size that
 * is not doubled reads half of a 32 bit number as if it were the whole of it,
 * with no error anywhere.
 *
 * The tool the dump comes from is not installed on every machine and is not
 * shipped with the application, so producing the dump is kept apart from
 * walking it. The tests below walk a document, and check the messages that come
 * out when the tool is not there.
 */

namespace
{
	/* A dump in the shape the tool prints: every entry states its own offset
	   and tag, every attribute states its own name, and every reference is an
	   offset. The identifiers carry a letter so that none of them is also a
	   valid decimal number, which keeps the offsets unambiguous. */
	const std::string dump = R"dump(<?xml version="1.0" encoding="UTF-8"?>
<ofd version="1.0">
  <!-- generated by ofd2000 -->
  <compilation_unit name="main.c">
    <die id="0x0000a000" tag="DW_TAG_base_type">
      <attribute name="DW_AT_name" value="unsigned int"/>
      <attribute name="DW_AT_byte_size" value="2"/>
      <attribute name="DW_AT_encoding" value="7"/>
    </die>
    <die id="0x0000a001" tag="DW_TAG_base_type">
      <attribute name="DW_AT_name" value="int"/>
      <attribute name="DW_AT_byte_size" value="1"/>
      <attribute name="DW_AT_encoding" value="5"/>
    </die>
    <die id="0x0000a002" tag="DW_TAG_typedef">
      <attribute name="DW_AT_name" value="uint16_t"/>
      <attribute name="DW_AT_type" ref="0x0000a003"/>
    </die>
    <die id="0x0000a003" tag="DW_TAG_base_type">
      <attribute name="DW_AT_name" value="unsigned short"/>
      <attribute name="DW_AT_byte_size" value="1"/>
      <attribute name="DW_AT_encoding" value="7"/>
    </die>
    <die id="0x0000a004" tag="DW_TAG_variable">
      <attribute name="DW_AT_name" value="counter"/>
      <attribute name="DW_AT_TI_symbol_name" value="_counter"/>
      <attribute name="DW_AT_location" value="DW_OP_addr 0x8000"/>
      <attribute name="DW_AT_type" ref="0x0000a000"/>
    </die>
    <die id="0x0000a005" tag="DW_TAG_variable">
      <attribute name="DW_AT_name" value="typed"/>
      <attribute name="DW_AT_location" value="DW_OP_addr 0x8040"/>
      <attribute name="DW_AT_type" ref="0x0000a002"/>
    </die>
    <die id="0x0000a006" tag="DW_TAG_enumeration_type">
      <attribute name="DW_AT_name" value="state_t"/>
      <attribute name="DW_AT_byte_size" value="1"/>
    </die>
    <die id="0x0000a007" tag="DW_TAG_variable">
      <attribute name="DW_AT_name" value="state"/>
      <attribute name="DW_AT_location" value="DW_OP_addr 0x8120"/>
      <attribute name="DW_AT_type" ref="0x0000a006"/>
    </die>
    <die id="0x0000a008" tag="DW_TAG_structure_type">
      <attribute name="DW_AT_name" value="Point"/>
      <die id="0x0000a009" tag="DW_TAG_member">
        <attribute name="DW_AT_name" value="x"/>
        <attribute name="DW_AT_data_member_location" value="0"/>
        <attribute name="DW_AT_type" ref="0x0000a003"/>
      </die>
      <die id="0x0000a00a" tag="DW_TAG_member">
        <attribute name="DW_AT_name" value="y"/>
        <attribute name="DW_AT_data_member_location" value="2"/>
        <attribute name="DW_AT_type" ref="0x0000a001"/>
      </die>
    </die>
    <die id="0x0000a00b" tag="DW_TAG_variable">
      <attribute name="DW_AT_name" value="origin"/>
      <attribute name="DW_AT_location" value="DW_OP_addr 0x9000"/>
      <attribute name="DW_AT_type" ref="0x0000a008"/>
    </die>
    <die id="0x0000a00c" tag="DW_TAG_structure_type">
      <attribute name="DW_AT_name" value="Line"/>
      <die id="0x0000a00d" tag="DW_TAG_member">
        <attribute name="DW_AT_name" value="from"/>
        <attribute name="DW_AT_data_member_location" value="0"/>
        <attribute name="DW_AT_type" ref="0x0000a008"/>
      </die>
      <die id="0x0000a00e" tag="DW_TAG_member">
        <attribute name="DW_AT_name" value="to"/>
        <attribute name="DW_AT_data_member_location" value="3"/>
        <attribute name="DW_AT_type" ref="0x0000a008"/>
      </die>
    </die>
    <die id="0x0000a00f" tag="DW_TAG_variable">
      <attribute name="DW_AT_name" value="segment"/>
      <attribute name="DW_AT_location" value="DW_OP_addr 0x9100"/>
      <attribute name="DW_AT_type" ref="0x0000a00c"/>
    </die>
    <die id="0x0000a010" tag="DW_TAG_array_type">
      <attribute name="DW_AT_name" value="buffer"/>
      <attribute name="DW_AT_type" ref="0x0000a003"/>
      <die id="0x0000a011" tag="DW_TAG_subrange_type">
        <attribute name="DW_AT_count" value="16"/>
      </die>
    </die>
    <die id="0x0000a012" tag="DW_TAG_variable">
      <attribute name="DW_AT_name" value="buffer"/>
      <attribute name="DW_AT_location" value="DW_OP_addr 0x1000"/>
      <attribute name="DW_AT_type" ref="0x0000a010"/>
    </die>
    <die id="0x0000a013" tag="DW_TAG_array_type">
      <attribute name="DW_AT_name" value="small"/>
      <attribute name="DW_AT_type" ref="0x0000a003"/>
      <die id="0x0000a014" tag="DW_TAG_subrange_type">
        <attribute name="DW_AT_upper_bound" value="3"/>
      </die>
    </die>
    <die id="0x0000a015" tag="DW_TAG_variable">
      <attribute name="DW_AT_name" value="small"/>
      <attribute name="DW_AT_location" value="DW_OP_addr 0x1100"/>
      <attribute name="DW_AT_type" ref="0x0000a013"/>
    </die>
    <die id="0x0000a016" tag="DW_TAG_array_type">
      <attribute name="DW_AT_name" value="points"/>
      <attribute name="DW_AT_type" ref="0x0000a008"/>
      <die id="0x0000a017" tag="DW_TAG_subrange_type">
        <attribute name="DW_AT_count" value="4"/>
      </die>
    </die>
    <die id="0x0000a018" tag="DW_TAG_variable">
      <attribute name="DW_AT_name" value="points"/>
      <attribute name="DW_AT_location" value="DW_OP_addr 0x1200"/>
      <attribute name="DW_AT_type" ref="0x0000a016"/>
    </die>
    <die id="0x0000a019" tag="DW_TAG_pointer_type">
      <attribute name="DW_AT_byte_size" value="1"/>
      <attribute name="DW_AT_type" ref="0x0000a003"/>
    </die>
    <die id="0x0000a01a" tag="DW_TAG_variable">
      <attribute name="DW_AT_name" value="pBuf"/>
      <attribute name="DW_AT_location" value="DW_OP_addr 0x2000"/>
      <attribute name="DW_AT_type" ref="0x0000a019"/>
    </die>
    <die id="0x0000a01b" tag="DW_TAG_variable">
      <attribute name="DW_AT_name" value="declaredOnly"/>
      <attribute name="DW_AT_declaration" value="1"/>
      <attribute name="DW_AT_location" value="DW_OP_addr 0x2100"/>
      <attribute name="DW_AT_type" ref="0x0000a000"/>
    </die>
    <die id="0x0000a01c" tag="DW_TAG_variable">
      <attribute name="DW_AT_name" value="inRegister"/>
      <attribute name="DW_AT_location" value="DW_OP_reg5"/>
      <attribute name="DW_AT_type" ref="0x0000a000"/>
    </die>
    <die id="0x0000a01d" tag="DW_TAG_variable">
      <attribute name="DW_AT_name" value="indexed"/>
      <attribute name="DW_AT_location" value="DW_OP_addrx 0x3"/>
      <attribute name="DW_AT_type" ref="0x0000a000"/>
    </die>
    <die id="0x0000a01e" tag="DW_TAG_variable">
      <attribute name="DW_AT_name" value="atZero"/>
      <attribute name="DW_AT_location" value="DW_OP_addr 0x0"/>
      <attribute name="DW_AT_type" ref="0x0000a000"/>
    </die>
    <die id="0x0000a01f" tag="DW_TAG_variable">
      <attribute name="DW_AT_name" value="noType"/>
      <attribute name="DW_AT_location" value="DW_OP_addr 0x2200"/>
    </die>
    <die id="0x0000a020" tag="DW_TAG_variable">
      <attribute name="DW_AT_location" value="DW_OP_addr 0x2300"/>
      <attribute name="DW_AT_type" ref="0x0000a000"/>
    </die>
    <die id="0x0000a021" tag="DW_TAG_base_type">
      <attribute name="DW_AT_name" value="long long"/>
      <attribute name="DW_AT_byte_size" value="4"/>
      <attribute name="DW_AT_encoding" value="5"/>
    </die>
    <die id="0x0000a022" tag="DW_TAG_variable">
      <attribute name="DW_AT_name" value="wide"/>
      <attribute name="DW_AT_location" value="DW_OP_addr 0x2400"/>
      <attribute name="DW_AT_type" ref="0x0000a021"/>
    </die>
  </compilation_unit>
</ofd>
)dump";

	/* The command the settings hold by default, spelled out so that the tests
	   below do not depend on the tool being installed. */
	const std::string absentTool = "variable-trace-absent-tool-9f3a2b";

	class TiOfdParserTest : public ::testing::Test
	{
	   protected:
		void SetUp() override
		{
			directory = std::filesystem::temp_directory_path() / "variable-trace-ti-ofd-parser-test";
			std::filesystem::create_directories(directory);

			/* Any file will do: nothing in these tests runs the tool, and the
			   walk does not touch the file system. */
			file = directory / "target.out";

			std::ofstream stream(file, std::ios::binary | std::ios::trunc);
			stream << "not a real object file";
		}

		void TearDown() override
		{
			std::error_code error;
			std::filesystem::remove_all(directory, error);
		}

		std::filesystem::path directory;
		std::filesystem::path file;
	};
}  // namespace

TEST(TiOfdParserValueTest, oneAddressUnitIsTwoBytes)
{
	EXPECT_EQ(TiOfdParser::bytesPerAddressUnit, 2u);
	EXPECT_EQ(TiOfdParser::toByteAddress(0), 0u);
	EXPECT_EQ(TiOfdParser::toByteAddress(1), 2u);
	EXPECT_EQ(TiOfdParser::toByteAddress(0x8000), 0x10000u);
}

TEST(TiOfdParserValueTest, theAddressOperationCarriesTheAddress)
{
	uint64_t address = 0;

	ASSERT_TRUE(TiOfdParser::decodeLocation("DW_OP_addr 0x8000", address));
	EXPECT_EQ(address, 0x8000u);

	/* Without the prefix the number is still read as hexadecimal, which is how
	   debug information is printed. */
	ASSERT_TRUE(TiOfdParser::decodeLocation("DW_OP_addr 8000", address));
	EXPECT_EQ(address, 0x8000u);
}

TEST(TiOfdParserValueTest, theSeparatorsAPrinterMayAddAreAccepted)
{
	uint64_t address = 0;

	ASSERT_TRUE(TiOfdParser::decodeLocation("DW_OP_addr: 0x1234", address));
	EXPECT_EQ(address, 0x1234u);

	ASSERT_TRUE(TiOfdParser::decodeLocation("DW_OP_addr | 0x40", address));
	EXPECT_EQ(address, 0x40u);
}

TEST(TiOfdParserValueTest, anIndexedAddressIsNotAnAddress)
{
	/* The operand indexes a section this walk does not open, so the entry is
	   dropped rather than guessed at. */
	uint64_t address = 0;

	EXPECT_FALSE(TiOfdParser::decodeLocation("DW_OP_addrx 0x3", address));
}

TEST(TiOfdParserValueTest, aLocationInARegisterIsNotAnAddress)
{
	uint64_t address = 0;

	EXPECT_FALSE(TiOfdParser::decodeLocation("DW_OP_reg5", address));
	EXPECT_FALSE(TiOfdParser::decodeLocation("DW_OP_fbreg -8", address));
	EXPECT_FALSE(TiOfdParser::decodeLocation("", address));
}

TEST(TiOfdParserValueTest, anOperationWithNoNumberUnderItIsNotAnAddress)
{
	uint64_t address = 0;

	EXPECT_FALSE(TiOfdParser::decodeLocation("DW_OP_addr", address));
}

TEST(TiOfdParserValueTest, anOperationWhoseNameStartsWithAnotherIsNotAMatch)
{
	/* The first operation name is a prefix of the second, so a match that runs
	   into another name character does not count. */
	uint64_t address = 0;

	EXPECT_FALSE(TiOfdParser::decodeLocation("DW_OP_address 0x10", address));
}

TEST_F(TiOfdParserTest, theParserNamesItself)
{
	TiOfdParser parser(nullptr, nullptr);

	EXPECT_EQ(IElfParser::nameOf(parser.getType()), "c2000");
	EXPECT_EQ(parser.getName(), "c2000");
	EXPECT_EQ(parser.getDescription(), "C2000: for TI C2000 targets, uses ofd2000.");
}

TEST_F(TiOfdParserTest, theToolCommandIsASetting)
{
	TiOfdParser parser(nullptr, nullptr);

	EXPECT_EQ(parser.getToolCommand(), "ofd2000");

	parser.setToolCommand("C:/tools/ofd2000.exe");

	EXPECT_EQ(parser.getToolCommand(), "C:/tools/ofd2000.exe");
}

TEST_F(TiOfdParserTest, aToolThatIsNotThereIsRefusedBeforeAnythingIsRead)
{
	TiOfdParser parser(nullptr, nullptr);
	parser.setToolCommand(absentTool);

	std::string reason;

	EXPECT_FALSE(parser.checkAvailability(reason));
	EXPECT_EQ(reason, "NOT FOUND. Please set the ofd2000 path manually");
	EXPECT_EQ(parser.getLastErrorMsg(), reason);
}

TEST_F(TiOfdParserTest, aToolThatIsThereIsAcceptedAndClearsTheMessage)
{
	TiOfdParser parser(nullptr, nullptr);
	parser.setToolCommand(absentTool);

	std::string reason;
	EXPECT_FALSE(parser.checkAvailability(reason));

	parser.setToolCommand(file.string());

	EXPECT_TRUE(parser.checkAvailability(reason));
	EXPECT_EQ(parser.getLastErrorMsg(), "");
}

TEST_F(TiOfdParserTest, aNameIsAcceptedOnlyWhenSomethingOfThatNameExists)
{
	EXPECT_TRUE(TiOfdParser::toolExists(file.string()));
	EXPECT_FALSE(TiOfdParser::toolExists((directory / "nothing-here.exe").string()));
	EXPECT_FALSE(TiOfdParser::toolExists(absentTool));
	EXPECT_FALSE(TiOfdParser::toolExists(""));
}

TEST_F(TiOfdParserTest, readingWithNoPathFails)
{
	TiOfdParser parser(nullptr, nullptr);

	EXPECT_FALSE(parser.parse(""));
	EXPECT_EQ(parser.getLastErrorMsg(), "ELF path not set or does not exist: ''");
}

TEST_F(TiOfdParserTest, readingAFileThatIsNotThereFails)
{
	TiOfdParser parser(nullptr, nullptr);

	EXPECT_FALSE(parser.parse((directory / "missing.out").string()));
	EXPECT_NE(parser.getLastErrorMsg().find("does not exist"), std::string::npos);
}

TEST_F(TiOfdParserTest, readingWithNoToolFailsAndSaysWhichSettingToChange)
{
	TiOfdParser parser(nullptr, nullptr);
	parser.setToolCommand(absentTool);

	EXPECT_FALSE(parser.parse(file.string()));
	EXPECT_EQ(parser.getLastErrorMsg(), "NOT FOUND. Please set the ofd2000 path manually");
}

TEST_F(TiOfdParserTest, everyScalarInTheDocumentIsReported)
{
	TiOfdParser parser(nullptr, nullptr);
	parser.parseDump(dump, "dump.xml");

	const IElfParser::SymbolMap symbols = parser.getParsedData();

	/* Eleven: three scalars, one of them reached through a typedef, one
	   enumeration, six fields of two structures, and one element of each of two
	   arrays. Everything else in the document is something the viewer cannot
	   read, and is listed in the test below. */
	ASSERT_EQ(symbols.size(), 11u);

	const auto scalars = {"counter", "typed", "state", "buffer[0]", "small[0]"};

	for (const char* name : scalars)
		EXPECT_EQ(symbols.count(name), 1u) << name;
}

TEST_F(TiOfdParserTest, aScalarIsReportedAtItsByteAddress)
{
	/* The file says 0x8000, which is 0x10000 once the address units are turned
	   into the bytes the probe addresses. */
	TiOfdParser parser(nullptr, nullptr);
	parser.parseDump(dump, "dump.xml");

	const IElfParser::SymbolMap symbols = parser.getParsedData();

	ASSERT_EQ(symbols.count("counter"), 1u);
	EXPECT_EQ(symbols.at("counter").address, 0x10000u);

	/* Two address units is a 32 bit number on this family, not a 16 bit one. */
	EXPECT_EQ(symbols.at("counter").type, Variable::Type::U32);
}

TEST_F(TiOfdParserTest, aTypedefIsFollowedToTheTypeItNames)
{
	TiOfdParser parser(nullptr, nullptr);
	parser.parseDump(dump, "dump.xml");

	const IElfParser::SymbolMap symbols = parser.getParsedData();

	ASSERT_EQ(symbols.count("typed"), 1u);
	EXPECT_EQ(symbols.at("typed").address, 0x10080u);
	EXPECT_EQ(symbols.at("typed").type, Variable::Type::U16);
}

TEST_F(TiOfdParserTest, anEnumerationIsReadAsTheIntegerItIsBuiltOn)
{
	TiOfdParser parser(nullptr, nullptr);
	parser.parseDump(dump, "dump.xml");

	const IElfParser::SymbolMap symbols = parser.getParsedData();

	ASSERT_EQ(symbols.count("state"), 1u);
	EXPECT_EQ(symbols.at("state").address, 0x10240u);
	EXPECT_EQ(symbols.at("state").type, Variable::Type::I16);
}

TEST_F(TiOfdParserTest, aStructureHasNoValueOfItsOwnSoItsFieldsAreReported)
{
	TiOfdParser parser(nullptr, nullptr);
	parser.parseDump(dump, "dump.xml");

	const IElfParser::SymbolMap symbols = parser.getParsedData();

	EXPECT_EQ(symbols.count("origin"), 0u);

	ASSERT_EQ(symbols.count("origin.x"), 1u);
	ASSERT_EQ(symbols.count("origin.y"), 1u);

	EXPECT_EQ(symbols.at("origin.x").address, 0x12000u);
	EXPECT_EQ(symbols.at("origin.x").type, Variable::Type::U16);

	/* The second field sits two address units into the structure, which is four
	   bytes the probe has to walk. */
	EXPECT_EQ(symbols.at("origin.y").address, 0x12004u);
	EXPECT_EQ(symbols.at("origin.y").type, Variable::Type::I16);
}

TEST_F(TiOfdParserTest, aStructureInsideAStructureIsFollowed)
{
	TiOfdParser parser(nullptr, nullptr);
	parser.parseDump(dump, "dump.xml");

	const IElfParser::SymbolMap symbols = parser.getParsedData();

	ASSERT_EQ(symbols.count("segment.from.x"), 1u);
	ASSERT_EQ(symbols.count("segment.from.y"), 1u);
	ASSERT_EQ(symbols.count("segment.to.x"), 1u);
	ASSERT_EQ(symbols.count("segment.to.y"), 1u);

	EXPECT_EQ(symbols.at("segment.from.x").address, 0x12200u);
	EXPECT_EQ(symbols.at("segment.from.y").address, 0x12204u);

	/* The second structure sits three units in, six bytes, and each of its
	   fields is reported with its own offset added to that. */
	EXPECT_EQ(symbols.at("segment.to.x").address, 0x12206u);
	EXPECT_EQ(symbols.at("segment.to.y").address, 0x1220au);

	EXPECT_EQ(symbols.at("segment.to.y").type, Variable::Type::I16);
}

TEST_F(TiOfdParserTest, anArrayIsNamedByItsFirstElementOnly)
{
	/* A buffer of a few thousand elements would otherwise fill the table with
	   names nobody asked for. */
	TiOfdParser parser(nullptr, nullptr);
	parser.parseDump(dump, "dump.xml");

	const IElfParser::SymbolMap symbols = parser.getParsedData();

	EXPECT_EQ(symbols.count("buffer"), 0u);
	EXPECT_EQ(symbols.count("buffer[1]"), 0u);

	ASSERT_EQ(symbols.count("buffer[0]"), 1u);
	EXPECT_EQ(symbols.at("buffer[0]").address, 0x2000u);
	EXPECT_EQ(symbols.at("buffer[0]").type, Variable::Type::U16);
}

TEST_F(TiOfdParserTest, theSizeOfAnArrayIsReadFromItsElementCount)
{
	/* The count can be stated as a number of elements or as the last index. */
	VariableHandler handler;

	auto third = std::make_shared<Variable>("third");
	third->setTrackedName("small[3]");
	handler.addVariable(third);

	auto past = std::make_shared<Variable>("past");
	past->setTrackedName("small[4]");
	handler.addVariable(past);

	TiOfdParser parser(&handler, nullptr);
	parser.parseDump(dump, "dump.xml");

	ASSERT_TRUE(parser.updateVariableMap(""));

	EXPECT_TRUE(third->getIsFound());
	EXPECT_EQ(third->getAddress(), 0x2206u);
	EXPECT_EQ(third->getType(), Variable::Type::U16);

	EXPECT_FALSE(past->getIsFound());
}

TEST_F(TiOfdParserTest, anElementOfAnArrayIsAnsweredByArithmetic)
{
	VariableHandler handler;

	auto fifth = std::make_shared<Variable>("fifth");
	fifth->setTrackedName("buffer[5]");
	handler.addVariable(fifth);

	auto beyond = std::make_shared<Variable>("beyond");
	beyond->setTrackedName("buffer[16]");
	handler.addVariable(beyond);

	/* The array itself has no address: only its elements do. */
	auto whole = std::make_shared<Variable>("whole");
	whole->setTrackedName("buffer");
	handler.addVariable(whole);

	auto malformed = std::make_shared<Variable>("malformed");
	malformed->setTrackedName("buffer[abc]");
	handler.addVariable(malformed);

	auto kept = std::make_shared<Variable>("kept");
	kept->setTrackedName("counter");
	kept->setShouldUpdateFromElf(false);
	kept->setAddress(0x1234);
	kept->setIsFound(true);
	handler.addVariable(kept);

	TiOfdParser parser(&handler, nullptr);
	parser.parseDump(dump, "dump.xml");
	ASSERT_TRUE(parser.updateVariableMap(""));

	EXPECT_TRUE(fifth->getIsFound());
	EXPECT_EQ(fifth->getAddress(), 0x200au);
	EXPECT_EQ(fifth->getType(), Variable::Type::U16);

	EXPECT_FALSE(beyond->getIsFound());
	EXPECT_FALSE(whole->getIsFound());
	EXPECT_FALSE(malformed->getIsFound());

	/* A variable marked as not updated from the symbol file is left as it was,
	   including the address it already had. */
	EXPECT_TRUE(kept->getIsFound());
	EXPECT_EQ(kept->getAddress(), 0x1234u);
}

TEST_F(TiOfdParserTest, theEntriesTheViewerCannotReadAreLeftOut)
{
	TiOfdParser parser(nullptr, nullptr);
	parser.parseDump(dump, "dump.xml");

	const IElfParser::SymbolMap symbols = parser.getParsedData();

	/* A pointer holds an address, which the viewer has nothing to draw. */
	EXPECT_EQ(symbols.count("pBuf"), 0u);

	/* A name that only declares a variable defined in another file has no
	   address in this one. */
	EXPECT_EQ(symbols.count("declaredOnly"), 0u);

	/* A location in a register, and one that is an index rather than an
	   address, have no address that can be read before the program runs. */
	EXPECT_EQ(symbols.count("inRegister"), 0u);
	EXPECT_EQ(symbols.count("indexed"), 0u);

	/* Zero is not an address, it is what a field that was never filled in
	   holds. */
	EXPECT_EQ(symbols.count("atZero"), 0u);

	/* No type, or no name, or a width the viewer has no representation for. */
	EXPECT_EQ(symbols.count("noType"), 0u);
	EXPECT_EQ(symbols.count("wide"), 0u);
	EXPECT_EQ(symbols.count(""), 0u);

	/* The element type of the last array is a structure, and an array of
	   structures would have to be expanded element by element. */
	EXPECT_EQ(symbols.count("points[0]"), 0u);
}

TEST_F(TiOfdParserTest, aDumpThatCannotBeReadLeavesWhatWasAlreadyAnswered)
{
	TiOfdParser parser(nullptr, nullptr);

	parser.parseDump("<not a document", "broken.xml");
	EXPECT_TRUE(parser.getParsedData().empty());

	parser.parseDump(dump, "dump.xml");
	ASSERT_EQ(parser.getParsedData().size(), 11u);

	parser.parseDump("", "empty.xml");
	EXPECT_EQ(parser.getParsedData().size(), 11u);
}
