/*
 * Target side integration example for the Variable-Trace recorder and serial
 * driver.
 *
 * It shows the three things the two modules need from the firmware: how the
 * bytes of an answer are put on the wire, where every received byte is handed
 * over, and where the sampling step is called from. Everything else - the
 * hardware setup, the clock tree, the pin configuration - is what CubeMX
 * generates and is not repeated here.
 *
 * The example is written against the STM32 HAL, which is what the sample
 * project of this repository uses. The three hooks are the only places an
 * integration touches: a port to another vendor's library keeps the same
 * structure and replaces the HAL calls.
 */

#include <stdint.h>

#include "stm32f1xx_hal.h"	/* replace with the header of your family */

#include "Recorder/recorder.h"
#include "SerialDriver/serialDriver.h"

/* Generated by CubeMX and owned by the application. */
extern UART_HandleTypeDef huart1;
extern TIM_HandleTypeDef htim2;

/* -------------------------------------------------------------------------
 * The variables the recorder can be told to capture
 *
 * They have to be real objects with a fixed address for as long as the host
 * holds that address, so none of them may live on a stack. The host learns
 * the address, the width and the declared type from the symbol file, and it
 * is the width it sends back that the target reads memory through.
 * ------------------------------------------------------------------------- */

volatile int32_t motorPosition = 0;
volatile uint16_t motorCurrent = 0;
volatile float motorSpeed = 0.0f;
volatile uint32_t controlLoopCounter = 0;

/* -------------------------------------------------------------------------
 * Serial driver: sending
 *
 * serialDriverSendData() is called from the receive interrupt, on the path
 * that handles a complete request frame. It therefore may not wait for the
 * bytes to leave the shift register, or the receive interrupt would be held
 * for the length of the answer and further bytes of an incoming frame would
 * be dropped.
 *
 * A small ring buffer drained by the transmit interrupt keeps the call short.
 * A ring of 128 bytes is comfortable: the longest answer the driver produces
 * is four bytes per variable plus two, and the host does not send the next
 * request before it has read the previous answer, so a second answer never
 * arrives while the first is still draining.
 * ------------------------------------------------------------------------- */

#define SERIAL_TX_RING_SIZE (128)

static volatile uint8_t txRing[SERIAL_TX_RING_SIZE];
static volatile uint16_t txHead = 0;
static volatile uint16_t txTail = 0;
static volatile uint8_t txBusy = 0;

static void serialDriverPumpTx(void);

/* Called by the driver, once per answer, with the bytes of that answer. */
void serialDriverSendData(uint8_t* buf, uint16_t size)
{
	uint16_t index = 0;

	for (index = 0; index < size; index++)
	{
		const uint16_t next = (uint16_t)((txHead + 1) % SERIAL_TX_RING_SIZE);

		if (next == txTail)
			break;	/* full - the host will time out and report a lost frame */

		txRing[txHead] = buf[index];
		txHead = next;
	}

	serialDriverPumpTx();
}

static void serialDriverPumpTx(void)
{
	if (txBusy != 0 || txTail == txHead)
		return;

	txBusy = 1;

	/* One byte at a time. The arithmetic stays obvious and the cost is
	   irrelevant next to the time the byte spends on the wire. */
	HAL_UART_Transmit_IT(&huart1, (uint8_t*)&txRing[txTail], 1);
}

/* -------------------------------------------------------------------------
 * Serial driver: receiving
 *
 * Every byte of every frame goes through serialDriverReceiveByte(), including
 * the two start bytes and the checksum. One byte per call, because the driver
 * is a state machine that keeps its own position.
 * ------------------------------------------------------------------------- */

static uint8_t rxByte = 0;

static void serialDriverStartReceive(void)
{
	HAL_UART_Receive_IT(&huart1, &rxByte, 1);
}

/* ---- the two HAL callbacks the example needs ---- */

void HAL_UART_RxCpltCallback(UART_HandleTypeDef* huart)
{
	if (huart != &huart1)
		return;

	serialDriverReceiveByte(rxByte);

	/* Armed again before returning, so the next byte is not missed. */
	serialDriverStartReceive();
}

void HAL_UART_TxCpltCallback(UART_HandleTypeDef* huart)
{
	if (huart != &huart1)
		return;

	txTail = (uint16_t)((txTail + 1) % SERIAL_TX_RING_SIZE);
	txBusy = 0;

	serialDriverPumpTx();
}

/* -------------------------------------------------------------------------
 * Recorder: the sampling step
 *
 * recorderStep() has to be called from a timer interrupt whose period equals
 * ____RECORDER_TIMEBASE_NS. On a 72 MHz part and the default time base of
 * 10 us that is a 100 kHz interrupt, so the handler has to stay small: the
 * step itself is a handful of byte copies and the callback does nothing but
 * call it.
 *
 * The host trusts the value in recorderDefines.h. It has no way to measure
 * the real period, so a time base that does not match this interrupt shows up
 * as a time axis that is off by a constant factor and never as an error.
 * ------------------------------------------------------------------------- */

void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef* htim)
{
	if (htim->Instance == TIM2)
		recorderStep();
}

/* -------------------------------------------------------------------------
 * Startup
 *
 * recorder.c and serialDriver.c already define and initialise the four
 * globals the host looks for, so there is nothing to fill in here.
 *
 * The headers only mention them through an extern inside their own inline
 * functions, which is not visible from outside, so the declarations have to
 * be repeated. They are then referenced once so that the linker cannot drop
 * the objects when the two modules are built into a static library and
 * nothing else names them.
 *
 * The volatile on the two settings structures matches their definitions. It
 * keeps the compiler from folding a read of a field the target never writes
 * once a run has begun.
 * ------------------------------------------------------------------------- */

extern ____Recorder ____recorder;
extern volatile ____RecorderSettings ____recorderSettings;
extern ____SerialDriver ____serialDriver;
extern volatile ____SerialDriverSettings ____serialDriverSettings;

void recorderPortInit(void)
{
	(void)____recorder;
	(void)____recorderSettings;
	(void)____serialDriver;
	(void)____serialDriverSettings;

	serialDriverStartReceive();

	HAL_TIM_Base_Start_IT(&htim2);
}
